insert into list_uf(uf,name) values('AC','Acre');
insert into list_uf(uf,name) values('AL','Alagoas');
insert into list_uf(uf,name) values('AM','Amazonas');
insert into list_uf(uf,name) values('AP','Amapá');
insert into list_uf(uf,name) values('BA','Bahia');
insert into list_uf(uf,name) values('CE','Ceará');
insert into list_uf(uf,name) values('DF','Distrito Federal');
insert into list_uf(uf,name) values('ES','Espírito Santo');
insert into list_uf(uf,name) values('GO','Goiás');
insert into list_uf(uf,name) values('MA','Maranhão');
insert into list_uf(uf,name) values('MG','Minas Gerais');
insert into list_uf(uf,name) values('MS','Mato Grosso do Sul');
insert into list_uf(uf,name) values('MT','Mato Grosso');
insert into list_uf(uf,name) values('PA','Pará');
insert into list_uf(uf,name) values('PB','Paraíba');
insert into list_uf(uf,name) values('PE','Pernambuco');
insert into list_uf(uf,name) values('PI','Piauí');
insert into list_uf(uf,name) values('PR','Paraná');
insert into list_uf(uf,name) values('RJ','Rio de Janeiro');
insert into list_uf(uf,name) values('RN','Rio Grande do Norte');
insert into list_uf(uf,name) values('RO','Rondônia');
insert into list_uf(uf,name) values('RR','Roraima');
insert into list_uf(uf,name) values('RS','Rio Grande do Sul (*)');
insert into list_uf(uf,name) values('SC','Santa Catarina');
insert into list_uf(uf,name) values('SE','Sergipe');
insert into list_uf(uf,name) values('SP','São Paulo');
insert into list_uf(uf,name) values('TO','Tocantins');